name: cd-backend-movies-uda

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  Test:
    runs-on: ubuntu-latest

    steps:
    - name: Check the git repo
      uses: actions/checkout@v3

    - name: Setup Python env
      uses:  actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install deps
      working-directory: solution/backend 
      run:  |
        python -m pip install --upgrade pip
        pip install pipenv
        pip install flake8

    - name: Test
      run: cd solution/backend && pipenv install pytest && pipenv run test

  Lint:
    runs-on: ubuntu-latest

    steps:
    - name: Check the git repository
      uses: actions/checkout@v3

    - name: Setup Python environment
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install backend deps
      working-directory: solution/backend 
      run:  |
        python -m pip install --upgrade pip
        pip install flake8
        pip install pipenv

    - name: Execute test lint
      run: cd solution/backend && pipenv run lint
      
  Build:
    needs: [Lint, Test]
    runs-on: ubuntu-latest
    
    steps:
    - name: Check the git repo
      uses: actions/checkout@v3



    - name: Configure Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
        
    - name: Login to AWS
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build and Push Docker Image to ECR
      working-directory: solution/backend
      env:
        IMAGE_TAG: latest
        REPO: backend
      run: |
        docker build --build-arg=REACT_APP_MOVIE_API_URL=http://localhost:5000 --tag 435720610029.dkr.ecr.us-east-1.amazonaws.com/$REPO:$IMAGE_TAG .
        docker push 435720610029.dkr.ecr.us-east-1.amazonaws.com/$REPO:$IMAGE_TAG
    - name: Update kubectl config 
      run:
       aws eks update-kubeconfig --name cluster --region us-east-1

    - name: Deploy backend docker image to EKS with kustomize
      working-directory: solution/backend/k8s
      env:
        IMAGE_TAG: latest
        REPO: backend
      run: |
        aws eks update-kubeconfig --name cluster --region us-east-1
        kustomize edit set image backend=435720610029.dkr.ecr.us-east-1.amazonaws.com/$REPO:$IMAGE_TAG
        kustomize build | kubectl apply -f -
